// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: portfolio/portfolio.proto

package portfolio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Portfolio_GetPerformance_FullMethodName = "/Portfolio/GetPerformance"
)

// PortfolioClient is the client API for Portfolio service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioClient interface {
	GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPerformanceResponse], error)
}

type portfolioClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioClient(cc grpc.ClientConnInterface) PortfolioClient {
	return &portfolioClient{cc}
}

func (c *portfolioClient) GetPerformance(ctx context.Context, in *GetPerformanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetPerformanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Portfolio_ServiceDesc.Streams[0], Portfolio_GetPerformance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetPerformanceRequest, GetPerformanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Portfolio_GetPerformanceClient = grpc.ServerStreamingClient[GetPerformanceResponse]

// PortfolioServer is the server API for Portfolio service.
// All implementations must embed UnimplementedPortfolioServer
// for forward compatibility.
type PortfolioServer interface {
	GetPerformance(*GetPerformanceRequest, grpc.ServerStreamingServer[GetPerformanceResponse]) error
	mustEmbedUnimplementedPortfolioServer()
}

// UnimplementedPortfolioServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServer struct{}

func (UnimplementedPortfolioServer) GetPerformance(*GetPerformanceRequest, grpc.ServerStreamingServer[GetPerformanceResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetPerformance not implemented")
}
func (UnimplementedPortfolioServer) mustEmbedUnimplementedPortfolioServer() {}
func (UnimplementedPortfolioServer) testEmbeddedByValue()                   {}

// UnsafePortfolioServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServer will
// result in compilation errors.
type UnsafePortfolioServer interface {
	mustEmbedUnimplementedPortfolioServer()
}

func RegisterPortfolioServer(s grpc.ServiceRegistrar, srv PortfolioServer) {
	// If the following call pancis, it indicates UnimplementedPortfolioServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Portfolio_ServiceDesc, srv)
}

func _Portfolio_GetPerformance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetPerformanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortfolioServer).GetPerformance(m, &grpc.GenericServerStream[GetPerformanceRequest, GetPerformanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Portfolio_GetPerformanceServer = grpc.ServerStreamingServer[GetPerformanceResponse]

// Portfolio_ServiceDesc is the grpc.ServiceDesc for Portfolio service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Portfolio_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Portfolio",
	HandlerType: (*PortfolioServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPerformance",
			Handler:       _Portfolio_GetPerformance_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "portfolio/portfolio.proto",
}
