// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: portfolio/portfolio.proto

package portfolio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPerformanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cash      int64       `protobuf:"varint,1,opt,name=cash,proto3" json:"cash,omitempty"`
	Positions []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
}

func (x *GetPerformanceRequest) Reset() {
	*x = GetPerformanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfolio_portfolio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceRequest) ProtoMessage() {}

func (x *GetPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_portfolio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_portfolio_portfolio_proto_rawDescGZIP(), []int{0}
}

func (x *GetPerformanceRequest) GetCash() int64 {
	if x != nil {
		return x.Cash
	}
	return 0
}

func (x *GetPerformanceRequest) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity int64  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfolio_portfolio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_portfolio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_portfolio_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetPerformanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nav int64   `protobuf:"varint,1,opt,name=nav,proto3" json:"nav,omitempty"`
	Pnl float64 `protobuf:"fixed64,2,opt,name=pnl,proto3" json:"pnl,omitempty"`
}

func (x *GetPerformanceResponse) Reset() {
	*x = GetPerformanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_portfolio_portfolio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceResponse) ProtoMessage() {}

func (x *GetPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_portfolio_portfolio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceResponse.ProtoReflect.Descriptor instead.
func (*GetPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_portfolio_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *GetPerformanceResponse) GetNav() int64 {
	if x != nil {
		return x.Nav
	}
	return 0
}

func (x *GetPerformanceResponse) GetPnl() float64 {
	if x != nil {
		return x.Pnl
	}
	return 0
}

var File_portfolio_portfolio_proto protoreflect.FileDescriptor

var file_portfolio_portfolio_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x2f, 0x70, 0x6f, 0x72, 0x74,
	0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x63, 0x61, 0x73, 0x68, 0x12, 0x27, 0x0a, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x3e, 0x0a, 0x08, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x22, 0x3c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x61, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x61, 0x76, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x6e, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x70, 0x6e, 0x6c, 0x32,
	0x52, 0x0a, 0x09, 0x50, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x12, 0x45, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x16,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_portfolio_portfolio_proto_rawDescOnce sync.Once
	file_portfolio_portfolio_proto_rawDescData = file_portfolio_portfolio_proto_rawDesc
)

func file_portfolio_portfolio_proto_rawDescGZIP() []byte {
	file_portfolio_portfolio_proto_rawDescOnce.Do(func() {
		file_portfolio_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(file_portfolio_portfolio_proto_rawDescData)
	})
	return file_portfolio_portfolio_proto_rawDescData
}

var file_portfolio_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_portfolio_portfolio_proto_goTypes = []any{
	(*GetPerformanceRequest)(nil),  // 0: GetPerformanceRequest
	(*Position)(nil),               // 1: Position
	(*GetPerformanceResponse)(nil), // 2: GetPerformanceResponse
}
var file_portfolio_portfolio_proto_depIdxs = []int32{
	1, // 0: GetPerformanceRequest.positions:type_name -> Position
	0, // 1: Portfolio.GetPerformance:input_type -> GetPerformanceRequest
	2, // 2: Portfolio.GetPerformance:output_type -> GetPerformanceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_portfolio_portfolio_proto_init() }
func file_portfolio_portfolio_proto_init() {
	if File_portfolio_portfolio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_portfolio_portfolio_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetPerformanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfolio_portfolio_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Position); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_portfolio_portfolio_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetPerformanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_portfolio_portfolio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_portfolio_portfolio_proto_goTypes,
		DependencyIndexes: file_portfolio_portfolio_proto_depIdxs,
		MessageInfos:      file_portfolio_portfolio_proto_msgTypes,
	}.Build()
	File_portfolio_portfolio_proto = out.File
	file_portfolio_portfolio_proto_rawDesc = nil
	file_portfolio_portfolio_proto_goTypes = nil
	file_portfolio_portfolio_proto_depIdxs = nil
}
